# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20171026_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_price',
            new_name='per_product_price',
        ),
    ]
